global:
  message: Welcome to Order service prod environment!!
server:
  port: 8085
message: Hello From Prod
spring:
  datasource:
    url:
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
